### ISSUE TITLE
Keep track of tags for messages that have been revealed

### ISSUE THREAD

**Issue by alxdavids** [brave-experiments/nested-sta-rs#2]
As well as what is included in the current output (including what has been added in https://github.com/alxdavids/sta-rs/pull/3) we need to keep track of the message tags (and layer encryption keys) that correspond to every revealed message during the Nested STAR recovery process. This is so that if we receive a new message in the future for the same epoch, we can compare tags for each layer and open any layers immediately without rerunning recovery.

Perhaps this would make sense to be exposed as a separate output struct, that essentially maps tags to layer encryption keys, and also includes the epoch tag that each tag corresponds to. This struct can then be used by the higher-level application when receiving new messages.

**Comment by alxdavids** [comment]
@DJAndries Just checking, but I think we can handle this at a higher-level than this codebase, right?

**Comment by DJAndries** [comment]
Yes, that's right. nested-star-aggregator already handles this by storing recovered keys in Postgres
